micronaut:
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
        generator:
          access-token:
            expiration: 300
  application:
    name: labrsmicronaut
  server:
    netty:
      access-logger:
        enabled: true
netty:
  default:
    allocator:
      max-order: 3