micronaut:

  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:abc123}"'
        generator:
          access-token:
            expiration: 300
    default-access: isAuthenticated()
  application:
    name: labrsmicronaut
  server:
    port: 8080
    cors:
      enabled: true
      web:
        allowedOrigins:
          http://localhost:4200/
        allowedMethods:
          - POST
          - PUT
          - GET
    netty:
      access-logger:
        enabled: true
netty:
  default:
    allocator:
      max-order: 3